# Generated by Django 3.1.1 on 2020-09-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='network_ip',
            field=models.GenericIPAddressField(unpack_ipv4=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='subnet',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='system',
            name='discovery_protocol',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='system',
            name='network_device_os',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='secret',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
