# Generated by Django 3.1.1 on 2020-09-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_auto_20200923_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='System',
            new_name='DeviceSystem',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='DeviceUser',
        ),
    ]
