# Generated by Django 3.1.1 on 2020-09-23 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0003_auto_20200923_1943'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceSystem',
            new_name='NetworkDeviceSystem',
        ),
        migrations.RenameModel(
            old_name='DeviceUser',
            new_name='NetworkDeviceUser',
        ),
    ]
