# Generated by Django 3.1.1 on 2020-09-23 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0005_auto_20200923_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='subnet',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)]),
        ),
    ]
