# Generated by Django 3.1.1 on 2020-09-23 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0007_auto_20200923_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('secret', models.CharField(max_length=50)),
                ('network_ip', models.GenericIPAddressField(unpack_ipv4=True)),
                ('subnet', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('network_device_os', models.CharField(max_length=50)),
                ('discovery_protocol', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceSystem',
        ),
        migrations.DeleteModel(
            name='DeviceUser',
        ),
        migrations.DeleteModel(
            name='Network',
        ),
    ]
