# Generated by Django 3.1.1 on 2020-09-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0008_auto_20200923_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configparameters',
            old_name='password',
            new_name='login_password',
        ),
        migrations.RenameField(
            model_name='configparameters',
            old_name='username',
            new_name='login_username',
        ),
        migrations.RenameField(
            model_name='configparameters',
            old_name='subnet',
            new_name='subnet_CIDR',
        ),
    ]
