# Generated by Django 3.1.1 on 2020-10-01 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config_app', '0016_availabledevices_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNMPConfigParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_location', models.CharField(default=None, max_length=50)),
                ('contact_details', models.EmailField(default=None, max_length=50)),
                ('enable_traps', models.BooleanField(null=True)),
                ('group_name', models.CharField(max_length=50)),
                ('snmp_user', models.CharField(max_length=50)),
                ('snmp_password', models.CharField(max_length=50)),
                ('snmp_encrypt_key', models.CharField(max_length=50)),
                ('snmp_host', models.GenericIPAddressField(unpack_ipv4=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
