# Generated by Django 3.1.1 on 2020-10-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0017_snmpconfigparameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configparameters',
            name='discovery_protocol',
        ),
        migrations.AlterField(
            model_name='snmpconfigparameters',
            name='contact_details',
            field=models.EmailField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='snmpconfigparameters',
            name='enable_traps',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='snmpconfigparameters',
            name='server_location',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
