# Generated by Django 3.1.1 on 2020-10-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0018_auto_20201006_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpconfigparameters',
            name='snmp_auth_protocol',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='snmpconfigparameters',
            name='snmp_privacy_protocol',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
