# Generated by Django 3.1.1 on 2020-10-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0020_auto_20201012_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpconfigparameters',
            name='configured',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
