# Generated by Django 3.1.1 on 2020-10-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0021_snmpconfigparameters_configured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snmpconfigparameters',
            name='configured',
        ),
    ]
