# Generated by Django 3.1.1 on 2020-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0022_remove_snmpconfigparameters_configured'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparameters',
            name='snmp_config_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
