# Generated by Django 3.1.1 on 2020-10-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0023_configparameters_snmp_config_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configparameters',
            name='snmp_config_id',
        ),
        migrations.AddField(
            model_name='configparameters',
            name='status',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
