# Generated by Django 3.1.1 on 2020-10-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0024_auto_20201026_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configparameters',
            name='status',
        ),
        migrations.AddField(
            model_name='configparameters',
            name='snmp_config_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
