# Generated by Django 3.1.1 on 2020-11-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0025_auto_20201026_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmpconfigparameters',
            name='traps_activated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
