# Generated by Django 3.1.1 on 2020-11-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0026_snmpconfigparameters_traps_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='configparameters',
            name='access_config_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
