# Generated by Django 3.1.1 on 2020-10-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_description', models.CharField(default=None, max_length=1000)),
                ('system_contact', models.CharField(default=None, max_length=50)),
                ('system_name', models.CharField(default=None, max_length=50)),
                ('system_location', models.CharField(default=None, max_length=50)),
                ('if_number', models.IntegerField(default=None, null=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(default=None, max_length=50)),
                ('interface_description', models.CharField(default=None, max_length=100)),
                ('interface_mtu', models.CharField(default=None, max_length=20)),
                ('interface_speed', models.CharField(default=None, max_length=20)),
                ('interface_physical_addr', models.CharField(default=None, max_length=50)),
                ('interface_admin_status', models.CharField(default=None, max_length=10)),
                ('interface_operational_status', models.CharField(default=None, max_length=10)),
                ('interface_ip', models.CharField(default=None, max_length=50)),
                ('device_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manage_app.devicemodel')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
