# Generated by Django 3.1.1 on 2020-10-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='system_description',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
