# Generated by Django 3.1.1 on 2020-10-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceinterface',
            name='interface_ip',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
