# Generated by Django 3.1.1 on 2020-10-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_auto_20201018_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='system_up_time',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
