# Generated by Django 3.1.1 on 2020-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0004_devicemodel_system_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinterface',
            name='interface_in_errors',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='interface_in_unicast_packets',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='interface_out_errors',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='interface_out_unicast_packets',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
