# Generated by Django 3.1.1 on 2020-10-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0005_auto_20201020_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='device_type',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
