# Generated by Django 3.1.1 on 2020-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0006_devicemodel_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinterface',
            name='lldp_neighbor_interace',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='lldp_neighbor_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
