# Generated by Django 3.1.1 on 2020-10-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0008_auto_20201022_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceinterface',
            old_name='lldp_neighbor_name',
            new_name='lldp_neighbor_hostname',
        ),
    ]
