# Generated by Django 3.1.1 on 2020-10-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0009_auto_20201023_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='full_system_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='system_name',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
