# Generated by Django 3.1.1 on 2020-10-30 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0011_devicetrapmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='trap_data',
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_address',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_agent_address',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_domain',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_enterprise',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_generic',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_uptime',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='variable_binds_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='VarBindModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trap_oid', models.CharField(default=None, max_length=30, null=True)),
                ('trap_data', models.CharField(default=None, max_length=200, null=True)),
                ('trap_model', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='manage_app.devicetrapmodel')),
            ],
        ),
    ]
