# Generated by Django 3.1.1 on 2020-10-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0012_auto_20201030_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='user',
        ),
    ]
