# Generated by Django 3.1.1 on 2020-11-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0013_remove_devicetrapmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_date',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
