# Generated by Django 3.1.1 on 2020-11-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0014_devicetrapmodel_trap_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='variable_binds_count',
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_string_data',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
