# Generated by Django 3.1.1 on 2020-11-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0015_auto_20201101_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='trap_agent_address',
        ),
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='trap_enterprise',
        ),
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='trap_generic',
        ),
        migrations.RemoveField(
            model_name='devicetrapmodel',
            name='trap_uptime',
        ),
        migrations.AddField(
            model_name='devicetrapmodel',
            name='trap_port',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
