# Generated by Django 3.1.1 on 2020-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0016_auto_20201104_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='management_ip',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
