# Generated by Django 3.1.1 on 2020-11-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0017_devicemodel_management_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicemodel',
            old_name='management_ip',
            new_name='hostname',
        ),
    ]
