# Generated by Django 3.1.1 on 2020-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0018_auto_20201116_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='ssh_session',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
